project:
  type: book
  output-dir: _site

book:
  title: "Introduction to Time Series Analysis"
  author: "Boyko Amarov"
  date: last-modified
  chapters:
    - index.ipynb
    - 01-Introduction.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
